print_info() {
    prin "$(color 7)┌───────────────────  Sys ────────────────────┐"
    prin "\n"
    prin  "$(color 7)"  "$USER"
    prin "\n"
    prin "$(color 7)│"
    prin "\n"
    info "$(color 7)󰣇" distro
    prin "\n"
    info "$(color 7)│ ├ " kernel
    info "$(color 7)│ ├ " de
    info "$(color 7)│ ├ " theme
    info "$(color 7)│ ├ " packages
    info "$(color 7)│ ├ " shell
    info "$(color 7)│ └ " term
    prin "$(color 7)│"
    prin "\n"
    info "$(color 7)" model
    prin "\n"
    info "$(color 7)│ ├ " cpu
    info "$(color 7)│ ├ " gpu
    info "$(color 7)│ ├ " memory
    info "$(color 7)│ ├ 󰍹" resolution
    info "$(color 7)│ └ 󰔟" uptime
    prin "$(color 7)│"
    prin "$(color 7)└───────────────────────── $(color 1) $(color 2) $(color 3) $(color 4) $(color 5) $(color 6) $(color 7) $(color 7)──────┘"
    
}

image_source="$HOME/.config/neofetch/custom-ascii.txt"
separator=" "
colors=(distro)
bold="off"
gap=0