general {
    hide_cursor = false
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 7
    brightness = 0.5
}

label {
    text=$TIME12
    halign = center
    valign = top
    font_family = FiraCode Nerd Font
}

image {
    monitor =
    path = $HOME/.face.icon
    rounding = -1
    size = 200
    border_size = 3
    border_color = rgba(255,255,255,1)
    outline_thickness=100
    position = 0,100
}

label {
    text=$USER
    position = 0,-35
    font_family = FiraCode Nerd Font
}

input-field {
    monitor =
    size = 350, 45
    rounding = -1
    outline_thickness = 3
    position = 0, -100
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(255,255,255,1)
    check_color=rgba(0,0,0,0)
    fail_color=rgb(143, 143, 143)
    hide_input = true
    hide_input_base_color = rgba(255,255,255,0)
    font_family = FiraCode Nerd Font
    font_color = rgb(143, 143, 143)
    placeholder_text = Enter Password
    fail_text = Password Incorrect
    fade_on_empty = false
}
